import {
  ArrowDown,
  ArrowLeft,
  Asterisk,
  BrainCircuit,
  ChevronDown,
  CircleAlert,
  CodeXml,
  Headset,
  House,
  Info,
  Link2,
  Megaphone,
  Minus,
  PenTool,
  Plus,
  Search,
  Send,
  Settings2,
  X,
  ArrowRight,
  ArrowUpRight,
  BookOpenCheck,
  BriefcaseBusiness,
  Building2,
  CalendarCheck2,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronRight,
  CircleCheck,
  Clock3,
  Compass,
  Crosshair,
  GraduationCap,
  HandHeart,
  Landmark,
  Layers,
  Lock,
  Mail,
  MapPin,
  Newspaper,
  Route,
  Scale,
  ShieldCheck,
  Signpost,
  Sparkles,
  Target,
  UserRound,
  UsersRound,
  Waypoints,
  type LucideProps,
} from "lucide-react";

/**
 * Icon system - one family (Lucide), one stroke weight (1.75), sizes on a
 * 14 / 16 / 18 / 20 / 22px scale. Use icons to aid scanning, not to fill space.
 *
 * Icon registry. Data files reference icons by name (a plain string) so they
 * stay serialisable - ready to come from a CMS or API later.
 */
const icons = {
  alert: CircleAlert,
  "arrow-down": ArrowDown,
  asterisk: Asterisk,
  brain: BrainCircuit,
  "chevron-down": ChevronDown,
  close: X,
  code: CodeXml,
  headset: Headset,
  home: House,
  info: Info,
  link: Link2,
  megaphone: Megaphone,
  minus: Minus,
  "pen-tool": PenTool,
  plus: Plus,
  search: Search,
  send: Send,
  settings: Settings2,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "book-open-check": BookOpenCheck,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarCheck2,
  chart: ChartNoAxesColumnIncreasing,
  check: Check,
  "check-circle": CircleCheck,
  "chevron-right": ChevronRight,
  clock: Clock3,
  compass: Compass,
  crosshair: Crosshair,
  graduation: GraduationCap,
  "hand-heart": HandHeart,
  landmark: Landmark,
  layers: Layers,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  news: Newspaper,
  route: Route,
  scale: Scale,
  shield: ShieldCheck,
  signpost: Signpost,
  sparkles: Sparkles,
  target: Target,
  user: UserRound,
  users: UsersRound,
  waypoints: Waypoints,
} as const;

export type IconName = keyof typeof icons;

type IconProps = LucideProps & { name: IconName };

export function Icon({ name, strokeWidth = 1.75, ...props }: IconProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={strokeWidth} {...props} />;
}
